export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline1: `구독 서비스를`,
  headline2: `찾아보세요`,
  descriptionOne: `동네 인증하면 반경 2km의`,
  descriptionTwo:`모든 구독서비스를 볼 수 있어요`,
  buttonLabel: "Get started",
  imgStart: false,
  img: "./images/gif/gif_1.gif",
  alt: "descrition1",
  dark: true,
  primary: true,
  darkText: false,
  second: false
};

export const homeObjTwo = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline1: `원하는 서비스를`,
  headline2: `구독하세요`,
  descriptionOne: `구독 결제부터 관리까지 한번에`,
  descriptionTwo:`UptoDoor에서 해결하세요`,
  buttonLabel: "Get started",
  imgStart: true,
  img: "./images/gif/gif_2.gif",
  alt: "descrition1",
  dark: true,
  primary: true,
  darkText: false,
  second: true
};

export const homeObjThree = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline1: `구독 서비스를`,
  headline2: `판매하세요`,
  descriptionOne: `사장님이세요? `,
  descriptionTwo: `가게 등록을 통해 이웃들에게`,
  descriptionThree:`우리가게 구독서비스를 알릴 수 있어요`,
  buttonLabel: "Get started",
  imgStart: false,
  img: "./images/americano.png",
  alt: "descrition1",
  dark: true,
  primary: true,
  darkText: false,
  second:false
};