module.exports = {
<<<<<<< HEAD
  Login: require('./Users/Login'),
  SignOut: require('./Users/Signout'),
  SignUp: require('./Users/Signup'),
  UserInfo: require('./Users/Userinfo'),
  Order: require('./Users/Order'),
  UserOrder: require('./Users/Userorder'),
  AdminInfo: require('./Admin/Admininfo'),
  Position: require('./Admin/Position'),
  Store: require('./Admin/Store'),
  Email: require('./Auth/Email'),
  EmailSend: require('./Auth/EmailSend'),
  Kakaologin: require('./Oauth/kakao/Login'),
  KakaoToken: require('./Oauth/kakao/Token'),
  Kakaosignup: require('./Oauth/kakao/Signup'),
  Naverlogin: require('./Oauth/naver/Login'),
  Naversignup: require('./Oauth/naver/Signup'),
  Address: require('./Map/Address'),
  StoreInfo: require('./Map/Storeinfo'),
  StoreMap: require('./Map/Store'),
};
=======
    Login: require('./Users/Login'),
    SignOut: require('./Users/Signout'),
    SignUp: require('./Users/Signup'),
    UserInfo: require('./Users/Userinfo'),
    UpdateUser: require('./Users/Updateuser'),
    UserOrder: require('./Users/Userorder'),
    Order: require('./Users/Order'),
    DeleteOrder: require('./Users/Deleteorder'),
    AdminInfo: require('./Admin/Admininfo'),
    Position: require('./Admin/Position'),
    Store: require('./Admin/Store'),
    StoreData: require('./Admin/Storedata'),
    UpdateStore: require('./Admin/Updatestore'),
    Email: require('./Auth/Email'),
    EmailSend: require('./Auth/EmailSend'),
    Kakaologin: require('./Oauth/kakao/Login'),
    Kakaosignup: require('./Oauth/kakao/Signup'),
    Naverlogin: require('./Oauth/naver/Login'),
    Naversignup: require('./Oauth/naver/Signup'),
    Address: require('./Map/Address'),
    StoreInfo: require('./Map/Storeinfo'),
    StoreMap: require('./Map/Store')
}
>>>>>>> 0131b6d52ddb6477b1dce232520d0df1f4a2f65e
